### ISSUE TITLE
SugarCloud

### ISSUE THREAD

**Issue by bickart** [sugarcrmlabs/BulkImport#16]
We have 1,000,000 accounts to load into **SugarCloud**. When will this be available for SugarCloud?

**Comment by esimonetti** [comment]
@bickart as mentioned in person, feel free to install a package in Sugar Cloud and try it out. Make sure you do notify support in advance, if you are planning to potentially overload the infrastructure.

An example of installable package can be found here: https://github.com/esimonetti/BulkImportInstallableExample
