### ISSUE TITLE
Module not allowed

### ISSUE THREAD

**Issue by arvigJustinBarber** [sugarcrmlabs/BulkImport#21]
I am call the "/rest/v11/BulkImport/records/av5_circuits" endpoint with this body
`{"records":[{"name":"test"}]}`
and a valid oauth-token but I get this error back. 
`{
    "error": "invalid_parameter",
    "error_message": "Module av5_circuits not allowed"
}` 
I have created the module in sugar and verified the name is correct. I am wondering if this issue is in SugarCRM or in this API?

**Comment by ShadMickelberry** [comment]
Hey there Justin.

I believe that error is coming from the line at the below link. 
https://github.com/sugarcrmlabs/BulkImport/blob/11b46d0e836d34c68ef31796b061924a4aa588af/src/custom/include/bulkimport/BulkImport.php#L415

Did you set up the config_override options for that module?

**Comment by arvigJustinBarber** [comment]
In was able to find that the configs where being set in config.php instead of config_override in a different format. I added the configs to the config.php file and it works. Thanks for your help.
